### ISSUE TITLE
Crash when adding/removing a contact to/from a roster group

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1159]
When adding or removing a contact to/from a roster group via `/group add group contact` or `/group remove group contact` profanity crashes.

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff66ab535 in __GI_abort () at abort.c:79
#2  0x00007ffff6702508 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff680d28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6708c1a in malloc_printerr (
    str=str@entry=0x7ffff680eff8 "double free or corruption (out)")
    at malloc.c:5341
#4  0x00007ffff670a730 in _int_free (av=0x7ffff6844c40 <main_arena>, 
    p=0x555555d63090, have_lock=<optimized out>) at malloc.c:4306
#5  0x00005555555a098d in _free_group_data (data=0x55555a167f90)
    at src/xmpp/roster.c:341
#6  0x000055555559033d in _iq_id_handler_free (handler=0x555555d60410)
    at src/xmpp/iq.c:259
#7  0x00007ffff71c6c5e in ?? ()
   from target:/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00005555555901d3 in _iq_handler (conn=0x555555b2b8e0, stanza=0x55555a14fce0, 
    userdata=0x555555ceb970) at src/xmpp/iq.c:217
#9  0x00007ffff6879ca5 in handler_fire_stanza (conn=conn@entry=0x555555b2b8e0, 
    stanza=stanza@entry=0x55555a14fce0) at src/handler.c:124
#10 0x00007ffff687695a in _handle_stream_stanza (stanza=0x55555a14fce0, 
    userdata=0x555555b2b8e0) at src/conn.c:1179
#11 0x00007ffff688270f in _end_element (userdata=0x555555cddf60, 
    name=<optimized out>) at src/parser_expat.c:190
#12 0x00007ffff4a863df in doContent (parser=parser@entry=0x555555c66400, startTagLevel=startTagLevel@entry=0, enc=<optimized out>, s=<optimized out>, 
    end=0x555555d59d7d "71a3fda3a186de</photo></x><x xmlns='http://jabber.org/protocol/muc#user'><item role='moderator' jid='REDACTED/profanity.eiM4wu' affiliation='owner'/><item role='moderator' jid='REDACTED"..., nextPtr=0x555555c66430, haveMore=1 '\001') at ../../src/lib/xmlparse.c:2924
#13 0x00007ffff4a8749c in contentProcessor (parser=0x555555c66400, start=<optimized out>, end=<optimized out>, endPtr=<optimized out>) at ../../src/lib/xmlparse.c:2552
#14 0x00007ffff4a899f8 in XML_ParseBuffer (isFinal=0, len=240, parser=0x555555c66400) at ../../src/lib/xmlparse.c:1988
#15 XML_ParseBuffer (parser=0x555555c66400, len=240, isFinal=0) at ../../src/lib/xmlparse.c:1957
#16 0x00007ffff68795dc in xmpp_run_once (ctx=0x555555ceb970, timeout=10) at src/event.c:263
#17 0x000055555558f0ca in connection_check_events () at src/xmpp/connection.c:104
#18 0x000055555558e5eb in session_process_events () at src/xmpp/session.c:255
#19 0x0000555555587fac in prof_run (log_level=0x555555635160 "INFO", account_name=0x0) at src/profanity.c:128
#20 0x000055555560f7ec in main (argc=1, argv=0x7fffffffe238) at src/main.c:172
```

## Expected Behavior
No crash.

## Current Behavior
Profanity crashes with SIGABRT.

## Environment

```
profanity -v
Profanity, version 0.6.0dev.master.9357726e
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16)
GTK icons: Enabled
```

**Comment by mdosch** [comment]
@jubalh I can confirm that it is working now. Thank you!
