### ISSUE TITLE
Segfault when using /msg with not existing contact

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1193]
The profanity client 0.7.0 from the debian bullseye/testing repo crashes with an segfault when you do `/msg someone` when someone is a not existing contact (e.g. typo).
It was reported downstream at debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=940724

## Expected Behavior
No crash, but an info that this contact is not existing.

## Current Behavior
Segfault.

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff695c45f in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00005555555a840e in _create_tab (win=win@entry=19, wintype=<optimized out>, 
    identifier=identifier@entry=0x55555d0b6490 "someone", highlight=highlight@entry=0) at src/ui/statusbar.c:201
#3  0x00005555555a8477 in status_bar_active (win=win@entry=19, wintype=<optimized out>, 
    identifier=identifier@entry=0x55555d0b6490 "someone") at src/ui/statusbar.c:218
#4  0x00005555555a4f98 in ui_focus_win (window=0x55555d0cac60) at src/ui/core.c:676
#5  ui_focus_win (window=window@entry=0x55555d0cac60) at src/ui/core.c:645
#6  0x00005555555bd76e in cmd_msg (window=0x55555578f710, command=<optimized out>, args=<optimized out>)
    at src/command/cmd_funcs.c:2152
#7  0x00005555555b9c27 in _cmd_execute (window=window@entry=0x55555578f710, 
    command=command@entry=0x55555a909890 "/msg", inp=inp@entry=0x55555d0d5f70 "/msg someone")
    at src/command/cmd_funcs.c:7936
#8  0x00005555555b9afe in cmd_process_input (inp=0x55555d0d5f70 "/msg someone", window=0x55555578f710)
    at src/command/cmd_funcs.c:139
#9  cmd_process_input (window=0x55555578f710, inp=inp@entry=0x55555d0d5f70 "/msg someone")
    at src/command/cmd_funcs.c:116
#10 0x0000555555588a80 in prof_run (log_level=<optimized out>, account_name=<optimized out>) at src/profanity.c:116
#11 0x000055555558525f in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:172
```

## Steps to Reproduce (for bugs)
* Open profanity
* Type `/msg NOT_EXISTING_CONTACT`

## Environment
Debian Testing

```
uname -a                                                                                    :(
Linux schlepptop 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
```
```
/usr/bin/profanity --version
Profanity, version 0.7.0
Copyright (C) 2012 - 2019 James Booth <jubalh@iodoru.org>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.4+)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
It's already fixed in master.

I released [0.7.1](https://github.com/profanity-im/profanity/releases/tag/0.7.1) now. Should be fixed in there.
