### ISSUE TITLE
Profanity crashes with SIGABRT

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1395]
Profanity was crashing while having an OX encrypted chat.

## Expected Behavior
No crash.

## Current Behavior
SIGABRT

```
Thread 1 "profanity" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 140737332887584, 8, 2259167317884516352, 140737488345936, 140737332800885, 0, 
            140737332800288, 0, 72057960543668928, 0, 93824994101952, 0, 0, 140737488345856, 140737488345888}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff69d055b in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x555555722600, sa_sigaction = 0x555555722600}, sa_mask = {
            __val = {140737488346336, 93827783032833, 93824994125312, 93824994125312, 93824994125312, 93824994125312, 
              93824994125315, 93824994140432, 93824994125312, 93824994140432, 0, 0, 0, 0, 0, 551189334720}}, 
          sa_flags = -155405691, sa_restorer = 0x5d00000000}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6a29038 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6b35f3e "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fffffffdda0, reg_save_area = 0x7fffffffdd30}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ffff6a303da in malloc_printerr (str=str@entry=0x7ffff6b37c30 "double free or corruption (out)")
    at malloc.c:5339
No locals.
#4  0x00007ffff6a32250 in _int_free (av=0x7ffff6b67b80 <main_arena>, p=0x55555e102cd0, have_lock=<optimized out>)
    at malloc.c:4314
        size = 8243124574718616608
        fb = <optimized out>
        nextchunk = 0x7265cb75d17590f0
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#5  0x00007ffff6bee189 in wresize () from target:/lib/x86_64-linux-gnu/libncursesw.so.6
No symbol table info available.
#6  0x00005555555b243d in win_resize (window=0x5555557d6c70) at src/ui/window.c:681
        subwin_cols = 36
        layout = 0x555557f0f990
        cols = 239
        __PRETTY_FUNCTION__ = "win_resize"
#7  0x00005555555c74a1 in wins_resize_all () at src/ui/window_list.c:730
        window = 0x5555557d6c70
        values = 0x55555e43d340
        curr = 0x55555e43d340
        current_win = 0x5555555b9721 <title_bar_resize+150>
#8  0x00005555555b6d38 in ui_resize () at src/ui/core.c:202
        w = {ws_row = 63, ws_col = 239, ws_xpixel = 0, ws_ypixel = 0}
        window = 0x1f5a2cb4beadb800
#9  0x00005555555b6b67 in ui_update () at src/ui/core.c:147
        current = 0x55555e1006b0
#10 0x000055555558e4eb in prof_run (log_level=0x555555650692 "WARN", account_name=0x0, config_file=0x0, log_file=0x0, theme_name=0x0) at src/profanity.c:132
        line = 0x0
#11 0x0000555555624cab in main (argc=1, argv=0x7fffffffe0e8) at src/main.c:181
        entries = {{long_name = 0x555555650697 "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x5555556d5778 <version>, description = 0x55555565069f "Show version information", arg_description = 0x0}, {long_name = 0x5555556506b8 "account", short_name = 97 'a', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556d5790 <account_name>, description = 0x5555556506c0 "Auto connect to an account on startup", arg_description = 0x0}, {long_name = 0x5555556506e6 "log", short_name = 108 'l', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556d5780 <log>, description = 0x5555556506f0 "Set logging levels, DEBUG, INFO, WARN (default), ERROR", arg_description = 0x555555650727 "LEVEL"}, {long_name = 0x55555565072d "config", short_name = 99 'c', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556d5798 <config_file>, description = 0x555555650738 "Use an alternative configuration file", arg_description = 0x0}, {long_name = 0x55555565075e "logfile", short_name = 102 'f', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556d5788 <log_file>, description = 0x555555650766 "Specify log filename", arg_description = 0x0}, {long_name = 0x55555565077b "theme", short_name = 116 't', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556d57a0 <theme_name>, description = 0x555555650781 "Specify theme name", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        error = 0x0
        context = 0x555555701a00
```

## Environment
Debian Bullseye (Testing)

```
Profanity, version 0.9.5dev.master.5a179572
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.4rc1)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
Did this happen again or was it also a mistake while running in GDB? :)

**Comment by mdosch** [comment]
It didn't happen again so far, so probably it was due to running in gdb.

**Comment by jubalh** [comment]
Feel free to reopen if needed.
