### ISSUE TITLE
SIGSEGV when connecting to an xmpp account with Biboumi irc services

### ISSUE THREAD

**Issue by be-neth** [profanity-im/profanity#1438]
Hi,

I get a SIGSEGV when connecting to my XMPP account which is a large account due to Biboumi accessing IRC services.
Everything works fine with 2 others XMPP client. (Conversations on Android & Dino on Linux)

## Expected Behavior

No crash.

## Current Behavior

I connect to my account with success, get my roster and channels and SIGSEGV happen here.

(I have deleted some personal information from this backtrace).

~~~
(gdb) bt full
#0  0x00007ffff695ba85 in __strlen_avx2 () from target:/usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff6866ab8 in __vfprintf_internal () from target:/usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff687784a in __vsnprintf_internal () from target:/usr/lib/libc.so.6
No symbol table info available.
#3  0x00007ffff6a152e6 in _nc_printf_string_sp () from target:/usr/lib/libncursesw.so.6
No symbol table info available.
#4  0x00007ffff6a0eab3 in vwprintw () from target:/usr/lib/libncursesw.so.6
No symbol table info available.
#5  0x00007ffff6a0ee08 in mvwprintw () from target:/usr/lib/libncursesw.so.6
No symbol table info available.
#6  0x00005555555b17ac in _status_bar_draw_tab (num=<optimized out>, pos=74, tab=<optimized out>)
    at src/ui/statusbar.c:401
        display_name = 0x55555640bd50 "### HIDDEN ###"
        display_num = <optimized out>
        is_current = 0
        show_number = 1
        show_name = 1
        show_read = <optimized out>
        status_attrs = 512
        display_num = <optimized out>
        is_current = <optimized out>
        show_number = <optimized out>
        show_name = <optimized out>
        show_read = <optimized out>
        status_attrs = <optimized out>
        display_name = <optimized out>
#7  status_bar_draw () at src/ui/statusbar.c:302
        tab = <optimized out>
        i = 3
        pos = <optimized out>
        max_tabs = 10
#8  0x00005555555b1d23 in _create_tab (win=win@entry=3, wintype=wintype@entry=WIN_MUC,
    identifier=<optimized out>, highlight=highlight@entry=0) at src/ui/statusbar.c:221
        true_win = <optimized out>
        tab = <optimized out>
#9  0x00005555555b1e17 in status_bar_active (win=win@entry=3, wintype=wintype@entry=WIN_MUC,
    identifier=<optimized out>) at src/ui/statusbar.c:227
No locals.
#10 0x00005555555ae82b in ui_room_join (
    roomjid=0x555555d65bc0 "### HIDDEN ###", focus=<optimized out>)
    at src/ui/core.c:813
        num = 3
        console = <optimized out>
        mucwin = 0x555556157450
        window = 0x555556157450
        nick = 0x55555578dd20 "### HIDDEN ###"
        privwins = <optimized out>
        curr = <optimized out>
#11 0x00005555555a8112 in sv_ev_muc_self_online (
### HIDDEN ###", show=0x555555ea9240 "online", status=0x0) at src/event/server_events.c:958
        jidp = <optimized out>
        mucwin = <optimized out>
        subject = <optimized out>
        pending_broadcasts = <optimized out>
        old_role = 0x5555556131e5 "none"
        old_affiliation = 0x5555556131e5 "none"
#12 0x000055555559c9b8 in _muc_user_self_handler (stanza=0x55555615ce60) at src/xmpp/presence.c:774
        config_required = 0
        actor = 0x0
        reason = 0x0
        nick = 0x555555ddd9b0 "### HIDDEN ###"
        status_str = 0x0
        jid = <optimized out>
        role = <optimized out>
        affiliation = <optimized out>
        x = <optimized out>
        show_str = 0x555555ea9240 "online"
        from = <optimized out>
        from_jid = 0x5555557955a0
        room = 0x555555d65bc0 "### HIDDEN ###"
        type = <optimized out>
        from = <optimized out>
        from_jid = <optimized out>
        room = <optimized out>
        type = <optimized out>
        new_nick = <optimized out>
        status_codes = <optimized out>
        new_jid = <optimized out>
        password = <optimized out>
        reason = <optimized out>
        actor = <optimized out>
        reason = <optimized out>
        actor = <optimized out>
        reason = <optimized out>
        config_required = <optimized out>
        actor = <optimized out>
        reason = <optimized out>
        nick = <optimized out>
        show_str = <optimized out>
        status_str = <optimized out>
        jid = <optimized out>
        role = <optimized out>
        affiliation = <optimized out>
        x = <optimized out>
        item = <optimized out>
#13 _muc_user_handler (stanza=0x55555615ce60) at src/xmpp/presence.c:888
        type = <optimized out>
        from = <optimized out>
        from_jid = <optimized out>
        type = <optimized out>
        from = <optimized out>
        from_jid = <optimized out>
#14 _presence_handler (conn=<optimized out>, userdata=<optimized out>, stanza=0x55555615ce60) at src/xmpp/presence.c:395
        text_size = <optimized out>
        cont = <optimized out>
        type = <optimized out>
        text = <optimized out>
        mucuser = <optimized out>
        text = <optimized out>
        text_size = <optimized out>
        cont = <optimized out>
        type = <optimized out>
        mucuser = <optimized out>
#15 _presence_handler (conn=<optimized out>, stanza=0x55555615ce60, userdata=<optimized out>) at src/xmpp/presence.c:357
        text = 0x55555615c190 "\334\334@\003PU"
        text_size = 266
        cont = <optimized out>
        type = <optimized out>
        mucuser = <optimized out>
#16 0x00007ffff69d2af1 in ?? () from target:/usr/lib/libstrophe.so.0
No symbol table info available.
#17 0x00007ffff69cf50d in ?? () from target:/usr/lib/libstrophe.so.0
No symbol table info available.
#18 0x00007ffff69dd34f in ?? () from target:/usr/lib/libstrophe.so.0
No symbol table info available.
#19 0x00007ffff593536b in ?? () from target:/usr/lib/libexpat.so.1
No symbol table info available.
#20 0x00007ffff59360cc in ?? () from target:/usr/lib/libexpat.so.1
No symbol table info available.
#21 0x00007ffff5938741 in XML_ParseBuffer () from target:/usr/lib/libexpat.so.1
No symbol table info available.
#22 0x00007ffff69d23f9 in xmpp_run_once () from target:/usr/lib/libstrophe.so.0
No symbol table info available.
#23 0x00005555555935bf in connection_check_events () at src/xmpp/connection.c:121
No locals.
#24 0x000055555558d9aa in prof_run (log_level=<optimized out>, account_name=<optimized out>, config_file=0x0, log_file=0x0, theme_name=<optimized out>) at src/profanity.c:130
        line = <optimized out>
#25 0x000055555558963d in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:180
        entries = {{long_name = 0x555555605f99 "version", short_name = 118 'v', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x5555556a28a8 <version>, description = 0x55555562bcfc "Show version information", arg_description = 0x0}, {long_name = 0x5555556142db "account", short_name = 97 'a', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556a2890 <account_name>, description = 0x55555562bf68 "Auto connect to an account on startup", arg_description = 0x0}, {long_name = 0x55555562b26f "log", short_name = 108 'l', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556a28a0 <log>, description = 0x55555562bf90 "Set logging levels, DEBUG, INFO, WARN (default), ERROR", arg_description = 0x55555562bd15 "LEVEL"}, {long_name = 0x5555556254a1 "config", short_name = 99 'c', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556a2888 <config_file>, description = 0x55555562bfc8 "Use an alternative configuration file", arg_description = 0x0}, {long_name = 0x55555562bd1b "logfile", short_name = 102 'f', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556a2898 <log_file>, description = 0x55555562bd23 "Specify log filename", arg_description = 0x0}, {long_name = 0x555555614663 "theme", short_name = 116 't', flags = 0, arg = G_OPTION_ARG_STRING, arg_data = 0x5555556a2880 <theme_name>, description = 0x55555562bd38 "Specify theme name", arg_description = 0x0}, {long_name = 0x0, short_name = 0 '\000', flags = 0, arg = G_OPTION_ARG_NONE, arg_data = 0x0, description = 0x0, arg_description = 0x0}}
        error = 0x0
        context = 0x5555556b2030
~~~

## Steps to Reproduce (for bugs)

Really don't know. Setup a Biboumi server connect to multiple IRC servers, multiple rooms, the bug can happen.

## Environment
~~~
Profanity, version 0.9.5dev.master.35aecd42
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.6)
GTK icons: Enabled
~~~

**Comment by jubalh** [comment]
I remember we had a similar report in the past that we fixed. Basically its about that some of our code expects some values where biboumi won't set them and we don't NULL check.

I'm not using biboumi but when I have time I will prepare some patches, and hopefully you can then test them and tell me whether it works :-)

**Comment by jubalh** [comment]
@be-neth Could you use ./configure-debug and compile without optimizations so that we could see the contents of some more variables?

Especially for:
```
#6  0x00005555555b17ac in _status_bar_draw_tab (num=<optimized out>, pos=74, tab=<optimized out>)
    at src/ui/statusbar.c:401
        display_name = 0x55555640bd50 "### HIDDEN ###"
        display_num = <optimized out>
        is_current = 0
        show_number = 1
        show_name = 1
        show_read = <optimized out>
        status_attrs = 512
        display_num = <optimized out>
        is_current = <optimized out>
        show_number = <optimized out>
        show_name = <optimized out>
        show_read = <optimized out>
        status_attrs = <optimized 
```

**Comment by jubalh** [comment]
I seem to remember that it didn't send us a MUC name or something..

**Comment by jubalh** [comment]
Which use case/channel creates the segfault?

**Comment by be-neth** [comment]
With debuging symbol 

Note: I have replaced the name of the IRC server to connect to with ##HiddenIRCNetwork##.

~~~
#6  0x00005555555bd2a4 in _status_bar_draw_tab (tab=0x555556296ff0, pos=92, num=3) at src/ui/statusbar.c:401
        display_name = 0x555556299660 "#linux%##HiddenIRCNetwork##"
        display_num = 3
        is_current = 0
        show_number = 1
        show_name = 1
        show_read = 1
        status_attrs = 512
~~~

**Comment by jubalh** [comment]
Can you join our MUC and tell me the name of the channel/server in private so I can try?

**Comment by be-neth** [comment]
I really don't know what is happening, but yesterday in Dino application, I re-configure the problematic room and now it is working again. (But really, I change nothing…)

I will keep track of this bug in the next week to see what is going on because I see sometimes SEGFAULT which seems related to this one, but not reproducible for the moment.
Please note that this bug seems related to Biboumi.

Anyway, many thanks for your quick support!

**Comment by jubalh** [comment]
@be-neth any news?

**Comment by be-neth** [comment]
no sorry.
Never see the crash this month…

**Comment by jubalh** [comment]
I guess you must have changed something in a setting of the IRC channel? Maybe some value was not set before and we got NULL and then later crashed because in XMPP that value would always be set. And we should still catch this and not segfault.

Do you have an idea what you changed?

**Comment by be-neth** [comment]
Like I said in my previous comment, I only re-setup the problematic channel with Dino Xmmp client, and profanity was not segfaulting anymore.
But don't worry, I keep track of this issue if the bug re-happen.
