### ISSUE TITLE
SIGABRT when OX + MAM

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1704]
## Expected Behavior
Retrieve some incomplete MAM and let me write normal ox messages.

## Current Behavior
Getting SIBABRT

## Possible Solution
I recently edited the `me:` related to akawolfs stamp change.
Also @paulfertser recently did https://github.com/profanity-im/profanity/pull/1674

## Steps to Reproduce (for bugs)
Frist time
1. /mam on
2. /ox start
3. Write some stuff

After that we get a SIGABRT when we do:
1. /ox start
2. Hello

while getting the MAM messages.

## Context
```
gdb$ p lookup_str>str
$2 = (gchar *) 0x17fae10 "default_"

#0  magazine_chain_pop_head (magazine_chunks=0x58d480) at ../glib/gslice.c:583                                                                                                                
(More stack frames follow...)   
#2  g_slice_alloc (mem_size=mem_size@entry=16) at ../glib/gslice.c:1063                                                                                                                       
#3  0x00007ffff6c4df3a in g_slice_alloc0 (mem_size=mem_size@entry=16) at ../glib/gslice.c:1098                                                                                                
#4  0x00007ffff6c16fb7 in g_error_allocate (domain=domain@entry=52, out_info=out_info@entry=0x7fffffffbbf0) at ../glib/gerror.c:708                                                           
#5  0x00007ffff6c1742d in g_error_new_steal (out_info=0x0, message=0x10ac940 "Key file does not have group “colours”", code=4, domain=52) at ../glib/gerror.c:722                             
#6  g_error_new_valist (domain=52, code=4, format=0x7ffff6c8b3f8 "Key file does not have group “%s”", args=args@entry=0x7fffffffbc50) at ../glib/gerror.c:764                                 
#7  0x00007ffff6c17abb in g_set_error (err=err@entry=0x7fffffffbd70, domain=<optimized out>, code=code@entry=4, format=format@entry=0x7ffff6c8b3f8 "Key file does not have group “%s”") at ../
glib/gerror.c:961                                                                                                                                                                             
#8  0x00007ffff6c2600b in g_key_file_get_value (key_file=key_file@entry=0x5ca640, group_name=0x4f6018 "colours", key=key@entry=0x4f6026 "bkgnd", error=error@entry=0x7fffffffbd70) at ../glib/
gkeyfile.c:1918                                                                                                                                                                               
#9  0x00007ffff6c26258 in g_key_file_get_string (key_file=0x5ca640, group_name=<optimized out>, key=0x4f6026 "bkgnd", error=0x0) at ../glib/gkeyfile.c:2024                                   
#10 0x00000000004ad255 in _theme_prep_bgnd (setting=0x4f6026 "bkgnd", def=0x4f5621 "default", lookup_str=0x1099aa0) at src/config/theme.c:644                                                 
#11 0x00000000004adf7c in theme_attrs (attrs=THEME_TEXT_THEM) at src/config/theme.c:1073                                                                                                      
#12 0x000000000045ab2b in _win_print_internal (window=0xc1cc60, show_char=0x17fa5b0 "%", pad_indent=0, time=0x109f9a0, flags=1, theme_item=THEME_TEXT_THEM, from=0x10ce9e0 "me", message=0x119
ff70 "hello", receipt=0x0) at src/ui/window.c:1642                                                                                                                                            
#13 0x000000000045a52e in _win_printf (window=0xc1cc60, show_char=0x17fa5b0 "%", pad_indent=0, timestamp=0x109f9a0, flags=1, theme_item=THEME_TEXT_THEM, display_from=0x10ce9e0 "me", from_jid
=0x10081e0 "me@me.org", message_id=0x703e70 "phyaIfrajW7S8zi99607bb81fdca737de85529f3a48fb1c48614523", message=0x4d2dc8 "%s") at src/ui/window.c:1505                                 
#14 0x000000000045917a in win_print_incoming (window=0xc1cc60, display_name_from=0x10ce9e0 "me", message=0x710800) at src/ui/window.c:1195                                                    
#15 0x0000000000472d7a in chatwin_incoming_msg (chatwin=0xc1cc60, message=0x710800, win_created=0) at src/ui/chatwin.c:286                                                                    
#16 0x0000000000453b74 in _sv_ev_incoming_ox (chatwin=0xc1cc60, new_win=0, message=0x710800, logit=1) at src/event/server_events.c:548                                                        
(More stack frames follow...) 
```

## Environment
Git 7acc044a527fd0d62afb4ff8742fc77e91f17e00 on https://github.com/profanity-im/profanity/pull/1703
theme: default

**Comment by jubalh** [comment]
Can't reproduce anymore after merging: https://github.com/profanity-im/profanity/pull/1703
@mdosch what about you?

**Comment by mdosch** [comment]
Looks like it's gone now.
