### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1733]
Profanity segfaults when receiving an (probably Ox encrypted message)

```
Thread 1 "profanity" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74	../sysdeps/x86_64/multiarch/strlen-avx2.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff741630f in __GI___strdup (s=s@entry=0x0) at strdup.c:41
#2  0x00005555555f49cc in plugins_pre_chat_message_display (barejid=0x555558105e50 "schlepptop@mdosch.de", resource=0x555559721510 "go-sendxmpp.d9e4ae3b", message=message@entry=0x0) at src/plugins/plugins.c:486
#3  0x00005555555c4608 in chatwin_incoming_msg (chatwin=chatwin@entry=0x55555de71430, message=message@entry=0x555559722950, win_created=win_created@entry=0) at src/ui/chatwin.c:315
#4  0x00005555555aac5e in _sv_ev_incoming_ox (logit=1, message=0x555559722950, new_win=0, chatwin=0x55555de71430) at src/event/server_events.c:549
#5  sv_ev_incoming_message (message=0x555559722950) at src/event/server_events.c:653
#6  0x000055555559c3a0 in _handle_chat (stanza=stanza@entry=0x55555971e350, is_mam=is_mam@entry=0, is_carbon=is_carbon@entry=0, result_id=result_id@entry=0x0, timestamp=timestamp@entry=0x0) at src/xmpp/message.c:1503
#7  0x000055555559d41c in _message_handler (conn=<optimized out>, userdata=<optimized out>, stanza=<optimized out>) at src/xmpp/message.c:264
#8  _message_handler (conn=<optimized out>, stanza=<optimized out>, userdata=<optimized out>) at src/xmpp/message.c:150
#9  0x00007ffff76bedf9 in handler_fire_stanza (conn=conn@entry=0x555555acf970, stanza=stanza@entry=0x55555971e350) at src/handler.c:132
#10 0x00007ffff76bc8dc in _handle_stream_stanza (stanza=0x55555971e350, userdata=0x555555acf970) at src/conn.c:1697
#11 0x00007ffff76ca17f in _end_element (name=<optimized out>, userdata=0x5555556d7400) at src/parser_expat.c:230
#12 _end_element (userdata=0x5555556d7400, name=<optimized out>) at src/parser_expat.c:213
#13 0x00007ffff6bb49e4 in doContent (parser=parser@entry=0x555555ad36f0, startTagLevel=startTagLevel@entry=0, enc=<optimized out>, s=<optimized out>, end=<optimized out>, nextPtr=0x555555ad3720, haveMore=1 '\001', 
    account=XML_ACCOUNT_DIRECT) at ../../src/lib/xmlparse.c:3047
#14 0x00007ffff6bb57aa in contentProcessor (parser=0x555555ad36f0, start=<optimized out>, end=<optimized out>, endPtr=<optimized out>) at ../../src/lib/xmlparse.c:2612
#15 0x00007ffff6bafcc1 in XML_ParseBuffer (parser=0x555555ad36f0, len=1480, isFinal=0, isFinal@entry=32767) at ../../src/lib/xmlparse.c:2009
#16 0x00007ffff6bb0308 in XML_Parse (parser=<optimized out>, 
    s=s@entry=0x7fffffffcfb0 "<message id='c7a0dece-c3ff5292-26a2e70c' xml:lang='en' to='martin@mdosch.de' from='schlepptop@mdosch.de/go-sendxmpp.d9e4ae3b'><store xmlns='urn:xmpp:hints'/><encryption namespace='urn:xmpp:openpgp:0' "..., 
    len=<optimized out>, isFinal=isFinal@entry=0) at ../../src/lib/xmlparse.c:1967
#17 0x00007ffff76ca3cb in parser_feed (parser=<optimized out>, 
    chunk=chunk@entry=0x7fffffffcfb0 "<message id='c7a0dece-c3ff5292-26a2e70c' xml:lang='en' to='martin@mdosch.de' from='schlepptop@mdosch.de/go-sendxmpp.d9e4ae3b'><store xmlns='urn:xmpp:hints'/><encryption namespace='urn:xmpp:openpgp:0' "..., len=<optimized out>) at src/parser_expat.c:371
#18 0x00007ffff76be764 in xmpp_run_once (ctx=0x555555ad5570, timeout=timeout@entry=10) at src/event.c:296
#19 0x000055555559519f in connection_check_events () at src/xmpp/connection.c:148
#20 0x000055555558e6dc in prof_run (log_level=<optimized out>, account_name=<optimized out>, config_file=0x0, log_file=0x0, theme_name=<optimized out>) at src/profanity.c:132
#21 0x000055555558a68d in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:186
```

## Environment
Debian unstable

```
profanity -v
Profanity, version 0.12.1dev.master.9ef34912
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.17.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled
```

**Comment by mdosch** [comment]
The fix in pr #1734 works. Thanks. :)
